# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NewrelicIntegrationE2e < Formula
  desc "Allows New Relic developers to run e2e on OHIs"
  homepage ""
  version "1.4.0-devel.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/newrelic-forks/newrelic-integration-e2e-action/releases/download/v1.4.0-devel.6/newrelic-integration-e2e-action_1.4.0-devel.6_darwin_amd64.tar.gz"
      sha256 "ca017d3c0fb8e9dee9aaf803ebe9cf788d823f18423f4a89ba9cc8317a515216"

      def install
        bin.install "newrelic-integration-e2e-action"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/newrelic-forks/newrelic-integration-e2e-action/releases/download/v1.4.0-devel.6/newrelic-integration-e2e-action_1.4.0-devel.6_darwin_arm64.tar.gz"
      sha256 "0d0c34f60f9e5cbb98e45d7e21995cbcc15e3d68f0ec8d27392e7627c8f9dd7c"

      def install
        bin.install "newrelic-integration-e2e-action"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/newrelic-forks/newrelic-integration-e2e-action/releases/download/v1.4.0-devel.6/newrelic-integration-e2e-action_1.4.0-devel.6_linux_arm64.tar.gz"
      sha256 "74aba7fb92c987947850e816e406f6cb9f7725e5af6e8f147f032957b7274914"

      def install
        bin.install "newrelic-integration-e2e-action"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/newrelic-forks/newrelic-integration-e2e-action/releases/download/v1.4.0-devel.6/newrelic-integration-e2e-action_1.4.0-devel.6_linux_amd64.tar.gz"
      sha256 "17ffdd7bfa537ec5d93f23bc5898d7e1d356dd10c539cd86058847123d88c707"

      def install
        bin.install "newrelic-integration-e2e-action"
      end
    end
  end
end
